# Generated by Django 4.2.1 on 2023-05-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShyftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shyft_firebaseid', models.CharField(max_length=100)),
                ('shyft_name', models.CharField(max_length=100)),
                ('shyft_familyname', models.CharField(max_length=100)),
                ('shyft_email', models.CharField(max_length=100, unique=True)),
                ('shyft_updatedOn', models.DateTimeField(auto_now=True)),
                ('shyft_userCreatedOn', models.DateTimeField(auto_now_add=True)),
                ('shyft_photoUrl', models.CharField(default='NA', max_length=500)),
                ('shyft_dob', models.DateTimeField(blank=True, null=True)),
                ('shyft_isdeleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
