# Generated by Django 4.2.1 on 2023-05-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shyftuser', '0002_shyftuser_shyft_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shyftuser',
            old_name='shyft_isdeleted',
            new_name='isdeleted',
        ),
    ]
