# Generated by Django 4.2.1 on 2023-05-26 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shyftuser', '0003_rename_shyft_isdeleted_shyftuser_isdeleted'),
        ('shyftresults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shyftresults',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shyftresults',
            name='shyftresult_score',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='shyftresults',
            name='shyftresult_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shyftuser.shyftuser'),
        ),
    ]
